apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prom
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
      lb.kubesphere.io/v1alpha1: openelb
      protocol.openelb.kubesphere.io/v1alpha1: layer2
      eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  selector: 
    app: alertmanager
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: 9093
